## **Подготовка к работе с данными**

Импорт всех необходимых библиотек

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from datetime import datetime
import plotly.express as px
from dotenv import load_dotenv
import os

Подгрузка предоставленных данных и предварительный анализ

In [12]:
visits = pd.read_csv('/Users/user/Downloads/visits_1k.csv')
visits.head(1000)

,uuid,platform,user_agent,date
0,1de9ea66-70d3-4a1f-8735-df5ef7697fb9,web,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2...,2023-03-01T13:29:22
1,f149f542-e935-4870-9734-6b4501eaf614,web,Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) Apple...,2023-03-01T16:44:28
2,f149f542-e935-4870-9734-6b4501eaf614,web,Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) Apple...,2023-03-06T06:12:36
3,08f0ebd4-950c-4dd9-8e97-b5bdf073eed1,web,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109...,2023-03-01T20:16:37
4,08f0ebd4-950c-4dd9-8e97-b5bdf073eed1,web,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109...,2023-03-05T17:42:47
...,...,...,...,...
995,8bc047ac-dc03-4a61-8037-7371f729fa34,web,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15....,2023-03-02T23:57:06
996,8bc047ac-dc03-4a61-8037-7371f729fa34,web,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15....,2023-03-07T23:05:08
997,3f78ac76-6f81-43ec-85e8-f3cf74fc8fdc,web,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,2023-03-02T12:47:09
998,3f78ac76-6f81-43ec-85e8-f3cf74fc8fdc,web,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,2023-03-07T00:07:34
999,1408b7ab-6450-4337-b57d-fd8a64b7fe97,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-03-02T10:10:51

In [9]:
visits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   uuid        1000 non-null   object
 1   platform    1000 non-null   object
 2   user_agent  1000 non-null   object
 3   date        1000 non-null   object
dtypes: object(4)
memory usage: 31.4+ KB

In [13]:
visits.describe()

,uuid,platform,user_agent,date
count,1000,1000,1000,1000
unique,519,3,28,996
top,251a0926-ece3-4d77-aa42-ab569fdf9fe2,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-03-01T08:01:45
freq,4,954,71,2

In [11]:
regs = pd.read_csv('/Users/user/Downloads/regs_1k.csv')
regs.head(1000)

,date,user_id,email,platform,registration_type
0,2023-03-01T00:25:39,8838849,joseph95@example.org,web,google
1,2023-03-01T14:53:01,8741065,janetsuarez@example.net,web,yandex
2,2023-03-01T14:27:36,1866654,robert67@example.org,web,google
3,2023-03-01T02:42:34,1577584,elam@example.net,web,apple
4,2023-03-01T10:27:14,4765395,stephanie68@example.net,web,yandex
...,...,...,...,...,...
995,2023-03-05T03:19:40,6414793,jerryrivera@example.com,android,google
996,2023-03-05T15:03:48,53167,laura65@example.net,android,google
997,2023-03-05T09:51:08,4969623,jasmine42@example.net,android,email
998,2023-03-05T16:25:59,7636873,imclaughlin@example.net,android,google
999,2023-03-05T11:17:41,7551697,jacobgarcia@example.org,android,google

In [10]:
regs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               1000 non-null   object
 1   user_id            1000 non-null   int64
 2   email              1000 non-null   object
 3   platform           1000 non-null   object
 4   registration_type  1000 non-null   object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB

In [18]:
regs['registration_type'].describe()

count      1000
unique        4
top       email
freq        446
Name: registration_type, dtype: object

In [17]:
regs['platform'].describe()

count        1000
unique          3
top       android
freq          517
Name: platform, dtype: object

In [19]:
regs['email'].describe()

count                       1000
unique                       997
top       kimberly90@example.com
freq                           2
Name: email, dtype: object